# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ccb281a5abd5fa18f2ea0372bbfef33d4c178247773083d844c53fe65e3ad688673d431227bf61cdacfcd201342cf4735e5a92611957fff66f18e024dbbc06b

test:
  secret_key_base: 7cd4c28e7a939bb1bc497164041c7c4bae79b752a4d7b7b12b47d5929a390195af9f5ec205751b23f2d4388070309fa1af56440a59c8e8079f85f232c2f82dda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
